# .github/workflows/laravel-ci.yml
name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, xml, bcmath, curl, mysql, zip

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Create .env and generate app key
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Laravel tests
        run: php artisan test

